##
# docker-compose.yml
#
##
version: '3.6'

services:
  checkmk:
    container_name: checkmk
    image: checkmk/check-mk-raw:2.0.0-latest
    ports:
      - "162:162/udp"
      - "514:514/udp"
      - "514:514/tcp"
      - "6557:6557/tcp"
      - "8080:5000/tcp"
    environment:
      - MAIL_RELAY_HOST=mailrelay.example.com
      - CMK_SITE_ID=cmknew
      - CMK_PASSWORD=XXX
      - CMK_LIVESTATUS_TCP=on
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    ulimits:
      nofile: 1024
    volumes:
      - ./monitoring:/omd/sites
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:5000"
    restart: unless-stopped

##################### Volumi ##############
volumes:
  checkmk_data:

