##
# docker-compose.yml
#
##
version: '3.6'

services:
  checkmk:
    container_name: 'checkmk'
    image: checkmk/check-mk-raw:2.2.0-latest
    hostname: 'checkmk.docker'
    ports:
      #- "162:162/udp"
      #- "514:514/udp"
      #- "514:514/tcp"
      #- "6557:6557/tcp"
      - '8000:8000'
      - '${CHECKMK_PORT:-8787}:5000/tcp'
    restart: unless-stopped
    environment:
      - TZ=Europe/Rome
      #- MAIL_RELAY_HOST=mailrelay.example.com
      - CMK_SITE_ID=cmkadmin
      - CMK_PASSWORD='${CHECKMK_PASSWORD:-XXX}'
      - CMK_LIVESTATUS_TCP=on
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    #ulimits:
    #  nofile: 1024
    volumes:
      - checkmk:/omd/sites
      - /etc/localtime:/etc/localtime:ro
      
#################### Volumes ###################
# external
# If set to true, specifies that this volume has been created outside of Compose. docker-compose up does not attempt to create it, and raises an error if it doesn't exist.
volumes:
  checkmk:
    external: ${VOLUMES_EXIST:-false}
    name: checkmk

